const imageRootPath = '.';
const broadcasts = new Map();

broadcasts.set(`Barrows dye`, {filename: `barrows_dye`, color: '#B6D7A8'});
broadcasts.set(`Shadow dye`, {filename: `shadow_dye`, color: '#D5A6BD'});
broadcasts.set(`Ice dye`, {filename: `ice_dye`, color: '#C9DAF8'});
broadcasts.set(`Third Age dye`, {filename: `third_age_dye`, color: '#CCCCCC'});
broadcasts.set(`Blood dye`, {filename: `blood_dye`, color: '#EA9999'});
broadcasts.set(`Third age full helmet`, {filename: `3a_melee_helm`, color: '#FFE599'});
broadcasts.set(`Third age platebody`, {filename: `3a_melee_top`, color: '#FFE599'});
broadcasts.set(`Third age platelegs`, {filename: `3a_melee_legs`, color: '#FFE599'});
broadcasts.set(`Third age kiteshield`, {filename: `3a_kiteshield`, color: '#FFE599'});
broadcasts.set(`Backstab cape`, {filename: `backstab_cape`, color: '#E6B8AF'});
broadcasts.set(`Third age mage hat`, {filename: `3a_mage_hat`, color: '#FFE599'});
broadcasts.set(`Third age robe top`, {filename: `3a_mage_top`, color: '#FFE599'});
broadcasts.set(`Third age robe`, {filename: `3a_mage_legs`, color: '#FFE599'});
broadcasts.set(`Third age amulet`, {filename: `3a_amulet`, color: '#FFE599'});
broadcasts.set(`Sack of effigies`, {filename: `sack_of_effigies`, color: '#EFEFEF'});
broadcasts.set(`Third age ranger coif`, {filename: `3a_coif`, color: '#FFE599'});
broadcasts.set(`Third age ranger body`, {filename: `3a_range_top`, color: '#FFE599'});
broadcasts.set(`Third age ranger chaps`, {filename: `3a_range_legs`, color: '#FFE599'});
broadcasts.set(`Third age vambraces`, {filename: `3a_range_vambraces`, color: '#FFE599'});
broadcasts.set(`Explosive barrel`, {filename: `explosive_barrel`, color: '#FFE599'});
broadcasts.set(`Third age druidic wreath`, {filename: `druidic_wreath`, color: '#FFE599'});
broadcasts.set(`Third age druidic robe top`, {filename: `druidic_top`, color: '#FFE599'});
broadcasts.set(`Third age druidic robe bottom`, {filename: `druidic_bottom`, color: '#FFE599'});
broadcasts.set(`Third age druidic staff`, {filename: `druidic_staff`, color: '#FFE599'});
broadcasts.set(`Third age druidic cloak`, {filename: `druidic_cloak`, color: '#FFE599'});
broadcasts.set(`Second-Age full helm`, {filename: `2a_melee_helm`, color: '#FFE599'});
broadcasts.set(`Second-Age platebody`, {filename: `2a_melee_body`, color: '#FFE599'});
broadcasts.set(`Second-Age platelegs`, {filename: `2a_melee_legs`, color: '#FFE599'});
broadcasts.set(`Second-Age sword`, {filename: `2a_melee_sword`, color: '#FFE599'});
broadcasts.set(`Orlando Smith's hat`, {filename: `orlando_smith_hat`, color: '#DD7E6B'});
broadcasts.set(`Second-Age mage mask`, {filename: `2a_mage_helm`, color: '#FFE599'});
broadcasts.set(`Second-Age robe top`, {filename: `2a_mage_body`, color: '#FFE599'});
broadcasts.set(`Second-Age robe bottom`, {filename: `2a_mage_legs`, color: '#FFE599'});
broadcasts.set(`Second-Age staff`, {filename: `2a_mage_staff`, color: '#FFE599'});
broadcasts.set(`Golden Compass`, {filename: `golden_compass`, color: '#B6D7A8'});
broadcasts.set(`Second-Age range coif`, {filename: `2a_range_coif`, color: '#FFE599'});
broadcasts.set(`Second-Age range top`, {filename: `2a_range_body`, color: '#FFE599'});
broadcasts.set(`Second-Age range legs`, {filename: `2a_range_legs`, color: '#FFE599'});
broadcasts.set(`Second-Age bow`, {filename: `2a_range_bow`, color: '#FFE599'});
broadcasts.set(`Blank`, {filename: `blank`, color: '#B6D7A8'});

export {broadcasts}